name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: APT Update
        run: apt update -y
      - name: APT Install
        run: apt install sudo -y
      - name: Install Forever
        run: sudo npm install forever -g
      - name: Install Dependencies
        run: npm install -y
      - name: Pre-Build
        run: |
              apt-get update
              # Install apt-transport-https
              apt-get install -y apt-transport-https
              # Use apt to install the Chrome dependencies
              apt-get install xvfb
              apt-get install -y libxcursor1
              apt-get install -y libgtk-3-dev
              apt-get install -y libxss1
              apt-get install -y libasound2
              apt-get install -y libnspr4
              apt-get install -y libnss3
              apt-get install -y libx11-xcb1
              ls ./node_modules/puppeteer/.local-chromium/
              # Print out missing libs
              echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome | grep not
      - name: Run Tests
        run: npm run test